# Site settings
title: Christabel website
email: chistalmails@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This blog . It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
paginate : 1

exclude: ['README.markdown']
